# Generated by Django 4.1.7 on 2023-03-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_order_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
