# Generated by Django 4.1.7 on 2023-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_available',
            field=models.BooleanField(default='true'),
        ),
    ]
