# Generated by Django 4.1.7 on 2023-03-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_is_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
